version: '3'

services:
  frontend:
    restart: always
    build:
      context: .
      args:
        PORT: ${PORT}
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
